# Generated by Django 3.0.6 on 2020-06-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakedgood',
            name='sTypes',
            field=models.CharField(blank=True, choices=[('BAGEL', 'Bagel'), ('BREAD', 'Bread'), ('COOKIE', 'Cookie'), ('CAKE', 'Cake'), ('PRETZEL', 'Pretzel')], max_length=20),
        ),
    ]
