# Generated by Django 3.0.6 on 2020-07-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_bakedgood_stypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='OtherBakedGood',
        ),
        migrations.RemoveField(
            model_name='bakedgood',
            name='sTypes',
        ),
        migrations.AddField(
            model_name='bakedgood',
            name='good_type',
            field=models.CharField(choices=[('BA', 'Bagel'), ('BR', 'Bread'), ('CO', 'Cookie'), ('CA', 'Cake'), ('PR', 'Pretzel')], default='BA', max_length=2),
        ),
        migrations.AddField(
            model_name='bakedgood',
            name='ingredients',
            field=models.ManyToManyField(to='example.Ingredient'),
        ),
    ]
